// Generated by the Supabase CLI. After applying migrations, run:
//   npx supabase gen types typescript --project-id <your-project-id> \
//     > src/shared/types/database.ts
// Until then this file is a placeholder.

export type Database = Record<string, never>
